version: 2
updates:
- package-ecosystem: npm
  directory: "/rendertron"
  schedule:
    interval: daily
  labels:
    - "dependencies"
- package-ecosystem: composer
  directory: "/tracer"
  schedule:
    interval: daily
  labels:
    - "dependencies"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
