version: '3.5'
services:
  tracer:
    image: dockette/rendertron:tracer
    environment:
      # Server to send requests over
      - TRACER_SERVER=http://localhost:4000/render/

      # Level of concurrency
      - TRACER_CONCURRENCY=5

      # Single sitemaps
      - TRACER_SRC_SITEMAP_1=https://dockette.org/sitemap1.xml
      - TRACER_SRC_SITEMAP_2=https://dockette.org/sitemap2.xml

      # Collection of sitemaps
      - TRACER_SRC_SITEMAP_LIST_1=https://dockette.org/sitemap2.xml
