name: Docker

on:
  push:
    branches: master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./proxy/Dockerfile
            tag: proxy

          - dockerfile: ./rendertron/Dockerfile
            tag: latest

          - dockerfile: ./tracer/Dockerfile
            tag: tracer

    name: Docker (dockette/rendertron:${{ matrix.tag }})

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfile }}
          push: true
          tags: dockette/rendertron:${{ matrix.tag }}
          platforms: linux/amd64,linux/arm64
