name: Docker

on:
  push:
    branches: master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./proxy
            tag: proxy

          - context: ./rendertron
            tag: latest

          - context: ./tracer
            tag: tracer

      fail-fast: false

    name: Docker (dockette/rendertron:${{ matrix.tag }})

    continue-on-error: "${{ matrix.tag == 'tracer' }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context  }}
          push: true
          tags: dockette/rendertron:${{ matrix.tag }}
          platforms: linux/amd64 # linux/arm64
